### ISSUE TITLE
Check for arel case node support

### ISSUE THREAD

**Issue by felixbuenemann** [take-five/acts_as_ordered_tree#35]
Arel master now supports CASE statements, based on the initial implementation from this gem and extended by me. So a check should be added if arel already has `Arel::Nodes::Case`.

We could also check for the arel version number, but the code is not yet in a released gem.

See rails/arel#400 for details and thanks again for the permission to use this code.

@take-five Should we wait for the next arel release and then add a version check or check if the constant is already defined?

**Comment by take-five** [comment]
Hello
First, thanks for your efforts to port it to Arel :)

Next, about your question. I think, there is no need to wait until next release, this feature can be checked with simple `defined?(Arel::Nodes::Case)` expression.

**Comment by felixbuenemann** [comment]
OK, I'll make a PR.
